version: '3.5'

volumes:
  persist-data:
  user-env:

services:
  webhacking-container:
    build: 
      context: webhacking-build
    hostname: webhacking-container
    restart: always
    volumes:
      - persist-data:/data
      - user-env:/home/user/      
      - /dev/shm:/dev/shm
      - /dev/net/tun:/dev/net/tun  
    env_file:
      - secrets/webhacking.env
    ports:   
      - "5900:5900"
      - "2222:22"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
 
