version: '3.5'

volumes:
  persist-data:
  user-env:

services:
  webhacking_yeswehack:
    build: 
      context: webhacking-build
    hostname: webhacking_yeswehack
    restart: always
    volumes:
      - persist-data:/data
      - user-env:/home/user/      
      - /dev/shm:/dev/shm
      - /dev/net/tun:/dev/net/tun  
    env_file:
      - secrets/webhacking.env
    expose:   
      - "5900"
      - "22"
    cap_add:
      - NET_ADMIN
 
